# Generated by Django 3.2.16 on 2023-01-29 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField()),
                ('telfone', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('cep', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
            ],
        ),
    ]
