# Generated by Django 3.2.16 on 2023-01-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='telfone',
            new_name='telefone',
        ),
    ]
